name: xcgrid_da
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  equatable: ^2.0.5
  recase: ^4.0.0
  slugid: ^1.1.0
  tuple: ^2.0.0
  decimal: ^2.2.0
  power_extensions: ^0.2.2
  path: ^1.8.0
  async: ^2.2.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  # bloc and di
  bloc: ^8.0.1
  hydrated_bloc: ^9.0.0
  get_it: ^7.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
